### ISSUE TITLE
Add Forgot Password Functionality using SendGrid mailing API and JWT.

### ISSUE THREAD

**Issue by nil1729** [nil1729/school_erp_node#5]

**Comment by vieee** [comment]
Hi @nil1729, I would love to work on this issue, could I..?

**Comment by nil1729** [comment]
Yes, You can. And sorry for I don't have proper documentation for How to start or run this project locally. Please install all dependencies. Create a `default.json` file in the following format on the `config` directory.  
```
{
    "mongoURI": " Mongo Atlas URI",
    "sessionSecret": " any random string",
    "GOOGLE_ID": "Google Cloud OAuth API Client ID",
    "GOOGLE_SECRET": "Google Cloud OAuth API Client Secret"
}
```
Please Find the necessary setup [here](https://github.com/nil1729/poll-app/blob/master/README.md#run-this-project-on-local-environment)
Thanks @vieee

**Comment by nil1729** [comment]
Hi, @vieee. Are you working on this issue?
Then I will be assigned it to you.
Thanks

**Comment by vieee** [comment]
Yes @nil1729, I'm working on it..

**Comment by nil1729** [comment]
Temporarily Closed this issue. because App doesn't have any Users right now.
